### ISSUE TITLE
Warning: Caught HttpError: Not Found

### ISSUE THREAD

**Issue by Mailaender** [flcdrg/remove-release-asset-action#144]
It seems something changed in the API? The error message does not contain many details:

```
Run flcdrg/remove-release-asset-action@v1.0.12
  with:
    release_id: 49852973
    asset_name: IP2LOCATION-LITE-DB1.IPV6.BIN.1.ZIP
  env:
    GITHUB_TOKEN: ***
Warning: Caught HttpError: Not Found
```

https://github.com/OpenRA/GeoIP-Database/runs/3653512578?check_suite_focus=true

**Comment by flcdrg** [comment]
Interesting. I'll see if I can figure out what's going on there.

**Comment by Mailaender** [comment]
The problem was that the user of the GitHub token did not have access to the repository. The GitHub API does throw error 404 while in fact it should be 403 instead, which is irritating.
